---
  - name: install ufw
    apt:
      name: ufw
      state: latest
 
  - name: enable ufw
    ufw:
      state: enabled
 
  - name: allow SSH from jumphost
    ufw:
      rule: allow
      port: ssh
      proto: tcp
      src: "{{ ssh_jumphost }}"

  - name: allowed services
    ufw:               
      rule: allow      
      port: "{{ item }}"
      state: enabled   
    with_items: "{{ allowed_services }}"
    when: allowed_services is defined

  - name: allowed ports
    ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      state: enabled
    with_items: "{{ allowed_ports }}"
    when: allowed_ports is defined     

  - name: reload ufw
    debug:
      msg: "Restarting ufw"
    notify: restart ufw
    changed_when: true
