---
  - name: install ufw
    apt:
      name: ufw
      state: latest
    notify: restart ufw

  - name: allow SSH from jumphost
    ufw:
      rule: allow
      port: ssh
      proto: tcp
      src: "{{ ssh_jumphost }}"
    notify: restart ufw

  - name: allowed services
    ufw:               
      rule: allow      
      port: "{{ item }}"
      state: enabled   
    with_items: "{{ allowed_services }}"
    notify: restart ufw    
    when: allowed_services is defined

  - name: allowed ports
    ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      state: enabled
    with_items: "{{ allowed_ports }}"
    notify: restart ufw             
    when: allowed_ports is defined     
