---
  - name: start ufw
    systemd:
      name: ufw
      enabled: yes
      state: started

  - name: restart ufw
    systemd:
      name: ufw
      enabled: yes
      state: restarted

  - name: stop ufw
    systemd:
      name: ufw
      enabled: yes
      state: stopped

  - name: start firewalld
    systemd:
      name: firewalld
      enabled: yes 
      state: started
      
  - name: restart firewalld
    systemd:  
      name: firewalld
      enabled: yes
      state: restarted
      
  - name: stop firewalld
    systemd:  
      name: firewalld
      enabled: yes
      state: stopped

